### PR TITLE
docs: remove verbose types

### PR DESCRIPTION
**Pull request by vinliao**
## Motivation

#614. Current iteration: https://github.com/vinliao/hubble/blob/md-docs-hide-sig-2/packages/js/docs/modules.md#functions.

## Change Summary

Remove the types in docs by adding a `hideSig.js` TypeDoc plugin and using it.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] Changes to the protocol specification have been merged

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

### CODE REVIEW

**Comment by vinliao** [comment]
See: https://github.com/vinliao/hubble/blob/md-docs-hide-sig-2/packages/js/docs/modules.md#makecastadd.

**Comment by vinliao** [comment]
Kinda awkward having the `function definition -> return -> example -> params` structure. Ideally the return section sits below params. The params are generated while the returns are written manually, still trying to figure out how to put a manually-written stuff below the generated params.

**Comment by varunsrin** [comment]
@vinliao let me know when ready for review, not sure if you are still planning to make more changes

**Comment by vinliao** [comment]
Sorry, should've asked for review when I've finished making the changes three days ago. Yes, please review it :)

**Comment by varunsrin** [comment]
Generally looks good, some minor nits on some comments but its easier for me to merge and make a new PR to address. Lets ship it!

**Pull request merged**
